Update pty4j to 0.12.6
Fixes:

14:22:18,256 ERROR org.apache.zeppelin.shell.terminal.service.TerminalService:64 - Exec_tty error:Cannot load native pty executor library
java.io.IOException: Exec_tty error:Cannot load native pty executor library
	at com.pty4j.unix.UnixPtyProcess.execInPty(UnixPtyProcess.java:272)
	at com.pty4j.unix.UnixPtyProcess.<init>(UnixPtyProcess.java:86)
	at com.pty4j.PtyProcessBuilder.start(PtyProcessBuilder.java:111)
	at com.pty4j.PtyProcess.exec(PtyProcess.java:78)
	at com.pty4j.PtyProcess.exec(PtyProcess.java:49)
	at org.apache.zeppelin.shell.terminal.service.TerminalService.initializeProcess(TerminalService.java:88)
	at org.apache.zeppelin.shell.terminal.service.TerminalService.lambda$onTerminalReady$0(TerminalService.java:62)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.RuntimeException: Cannot load native pty executor library
	at com.pty4j.unix.PtyHelpers.getPtyExecutor(PtyHelpers.java:257)
	at com.pty4j.unix.PtyHelpers.execPty(PtyHelpers.java:430)
	at com.pty4j.unix.UnixPtyProcess.exec(UnixPtyProcess.java:333)
	at com.pty4j.unix.UnixPtyProcess$Reaper.execute(UnixPtyProcess.java:389)
	at com.pty4j.unix.UnixPtyProcess$Reaper.run(UnixPtyProcess.java:395)

Signed-off-by: Martin Tzvetanov Grigorov <mgrigorov@apache.org>